spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billing_db
    username: root
    password: Chennai@330
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

menu:
  file:
    path: "D:/files/menu.csv"
